/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp6;

import javax.swing.JInternalFrame;

/**
 *
 * @author magus919
 */
public class Menu extends javax.swing.JFrame {
private static Directorio dir=new Directorio();

    /**
     * Creates new form Menu
     */
     public static Directorio getDirectorio(){
         return dir;
     }
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void centrarVentanaInterna(JInternalFrame internalFrame){
        int x= (escritorio.getWidth()/2)- internalFrame.getWidth()/2;
        int y= (escritorio.getHeight()/2)- internalFrame.getHeight()/2;
        if(internalFrame.isShowing()){
            internalFrame.setLocation(x, y);
        }else {
            escritorio.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAgregarClientes = new javax.swing.JMenu();
        jmiAgregarClientes = new javax.swing.JMenuItem();
        jmiBusquedadeCliente = new javax.swing.JMenuItem();
        jmiBorrarCliente = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        escritorio.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jmAgregarClientes.setText("Directorio Teléfonico");
        jmAgregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarClientesActionPerformed(evt);
            }
        });

        jmiAgregarClientes.setText("Agregar Clientes");
        jmiAgregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarClientesActionPerformed(evt);
            }
        });
        jmAgregarClientes.add(jmiAgregarClientes);

        jmiBusquedadeCliente.setText("Búsqueda de Clientes");
        jmiBusquedadeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBusquedadeClienteActionPerformed(evt);
            }
        });
        jmAgregarClientes.add(jmiBusquedadeCliente);

        jmiBorrarCliente.setText("Borrar Cliente");
        jmiBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarClienteActionPerformed(evt);
            }
        });
        jmAgregarClientes.add(jmiBorrarCliente);

        jMenuBar1.add(jmAgregarClientes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jmAgregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarClientesActionPerformed

    }//GEN-LAST:event_jmAgregarClientesActionPerformed

    private void jmiAgregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarClientesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AgregarClientes agg =new AgregarClientes();
        agg.setVisible(true);
        escritorio.add(agg);
        centrarVentanaInterna(agg);
    }//GEN-LAST:event_jmiAgregarClientesActionPerformed

    private void jmiBusquedadeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBusquedadeClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BusquedadeCliente bdc =new BusquedadeCliente();
        bdc.setVisible(true);
        escritorio.add(bdc);
        centrarVentanaInterna(bdc);
    }//GEN-LAST:event_jmiBusquedadeClienteActionPerformed

    private void jmiBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BorrarClientes brc =new BorrarClientes();
        brc.setVisible(true);
        escritorio.add(brc);
        centrarVentanaInterna(brc);
    }//GEN-LAST:event_jmiBorrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmAgregarClientes;
    private javax.swing.JMenuItem jmiAgregarClientes;
    private javax.swing.JMenuItem jmiBorrarCliente;
    private javax.swing.JMenuItem jmiBusquedadeCliente;
    // End of variables declaration//GEN-END:variables
}
